name: Merge Dev to Main

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev branch
        run: git merge dev

      - name: Push changes to main branch
        run: git push origin main